chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.action === "checkAI") {
    (async () => {
      try {
        const GEMINI_API_KEY = "AIzaSyCICniFq5Uo4wAFCWU7jI9OIPyIM4aRryM";
        const GEMINI_API_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-05-20:generateContent?key=${GEMINI_API_KEY}`;
        const prompt = `Analyze the following text and determine if it was likely generated by an AI. Respond with a single word: "Yes" if it is likely AI-generated, and "No" if it is not. Text: "${message.text}"`;

        const response = await fetch(GEMINI_API_URL, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            contents: [{ parts: [{ text: prompt }] }]
          })
        });

        if (!response.ok) {
          throw new Error(`API error: ${response.status}`);
        }

        const data = await response.json();
        const resultText = data.candidates?.[0]?.content?.parts?.[0]?.text || "";
        const cleanResult = resultText.trim().toLowerCase();
        const isAi = cleanResult === "yes" || cleanResult === "no" ? cleanResult === "yes" : false;

        sendResponse({ result: isAi });
      } catch (error) {
        console.error("Background API error:", error);
        sendResponse({ error: error.message });
      }
    })();

    // ✅ Important: keep the channel open for async response
    return true;
  }
});
