chrome.runtime.onMessage.addListener(async (message, sender, sendResponse) => {
  if (message.action === "checkAI") {
    try {
      const GEMINI_API_KEY = "AIzaSyBACWjUUH5nrY-kpBzYASAdEks5fAaRRQs";
      const GEMINI_API_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-05-20:generateContent?key=${GEMINI_API_KEY}`;
      const prompt = `Analyze the following text and determine if it was likely generated by an AI. Respond with a single word: "Yes" if it is likely AI-generated, and "No" if it is not. Text: "${message.text}"`;

      const response = await fetch(GEMINI_API_URL, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }]
        })
      });

      const data = await response.json();
      const resultText = data.candidates?.[0]?.content?.parts?.[0]?.text || "";
      const isAi = resultText.trim().toLowerCase().includes("yes");

      sendResponse({ result: isAi });
    } catch (error) {
      console.error("Background API error:", error);
      sendResponse({ error: error.message });
    }
  }
  return true; // keeps the channel open for async response
});
